#!/bin/sh

if [ -d "diy-build" ]; then
	sudo rm -rf diy-build
fi

sudo mkdir diy-build && cd diy-build && sudo lb config
sudo cp /usr/share/doc/live-build/examples/auto/* auto/

cd ..

if [ ! -f "./build" ]; then
	cp ./buildx ./build
fi
sudo cp ./build ./diy-build
sudo ./update


