#!/bin/bash
#diy User Set-up

set -e

if [ ! -d "/home/$USER/.config/diy" ]; then
	mkdir /home/$USER/.config/diy
fi

if [ ! -f "/home/$USER/.config/diy/diy-setup" ]; then

    if [ -f "/home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js > /dev/null 2>&1
    fi

    ln -s /usr/share/backgrounds /home/$USER/images/wallpapers/shared

    if [ "$USER" != "diylive" ]; then
		sed -i".bak" '/<!-- installer start -->/,/<!-- installer end -->/d' /etc/skel/.jwmrc
		rm /etc/skel/.jwmrc.bak
		if [ -f "/home/$USER/.jwmrc" ]; then
			rm /home/$USER/.jwmrc
		fi
		cp /etc/skel/.jwmrc /home/$USER/.jwmrc
	fi

	touch /home/$USER/.config/diy/diy-setup
    chown -R $USER:$USER /home/$USER
fi

xdg-user-dirs-update

exit 0
